### PR TITLE
support url-encoded ror identifier string

### PR DESCRIPTION
**Pull request by mfenner**
Support ROR ID in formats `ror.org%2F0w7hudk23` or `https%3A%2F%2Fror.org%2F0w7hudk23`.

### CODE REVIEW

**Comment by mfenner** [comment]
@dtkaczyk I added some tests, but don't understand the codebase enough at this point. Could you make the necessary changes?

**Comment by dtkaczyk** [comment]
I believe everything works ok now.

BTW, it seems that some of the requested changes in my original review were already done in the initial commits. Sorry for this confusion.

**Comment by mfenner** [comment]
Thanks @dtkaczyk.

**Comment by mfenner** [comment]
@dtkaczyk I deployed the changes to production. https://api.ror.org/organizations/ror.org%2F04wxnsj81 does't work, but https://api.ror.org/organizations/ror.org/04wxnsj81 does, as does https://api.ror.org/organizations?query=ror.org%2F04wxnsj81. Am I missing something?

**Comment by dtkaczyk** [comment]
It works for me. Maybe something is cached somewhere?

**Comment by mariagould** [comment]
@dtkaczyk I agree I think this can be closed but I don't seem to have the ability to close it.

**Pull request merged**
